In [140]:
!pip -q install pandas

In [141]:
import pandas as pd
import json
from datetime import datetime

In [142]:
flight_cols = [
    "FlightDate",
    "Quarter",
    "Year",
    "Month",
    "DayofMonth",
    "DepTime",
    "DepDel15",
    "CRSDepTime",
    "DepDelayMinutes",
    "Origin",
    "Dest",
    "ArrTime",
    "CRSArrTime",
    "ArrDel15",
    "ArrDelayMinutes",
]

In [143]:
airports = ["ATL", "CLT", "DEN", "DFW", "EWR", "IAH", "JFK", "LAS", "LAX", "MCO", "MIA", "ORD", "PHX", "SEA", "SFO"]

def load_flight_data(year):
    flight_data = pd.DataFrame()
    for month in range(1, 13):
        data_path = f"flight_data/{year}"
        file_path = f"{data_path}/On_Time_On_Time_Performance_{year}_{month}.csv"
        try:
            df = pd.read_csv(file_path)
            df = df[(df["Origin"].isin(airports)) & (df["Dest"].isin(airports))]
            df = df[flight_cols]
            flight_data = pd.concat([flight_data, df], ignore_index=True)
        except FileNotFoundError:
            print(f"File not found: {file_path}")
    return flight_data

In [144]:
flight_data_2016 = load_flight_data(2016)
flight_data_2017 = load_flight_data(2017)

flight_data = pd.concat([flight_data_2016, flight_data_2017], ignore_index=True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84,85) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,69,76,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_16488\4155471070.py:9: DtypeWarning: Columns (48,77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [167]:
flight_data

,FlightDate,Quarter,Year,Month,DayofMonth,DepTime,DepDel15,CRSDepTime,DepDelayMinutes,Origin,Dest,ArrTime,CRSArrTime,ArrDel15,ArrDelayMinutes
0,2016-01-01,1,2016,1,1,741.0,0.0,745,0.0,SEA,JFK,1610.0,1602,0.0,8.0
1,2016-01-02,1,2016,1,2,737.0,0.0,745,0.0,SEA,JFK,1613.0,1602,0.0,11.0
2,2016-01-03,1,2016,1,3,743.0,0.0,745,0.0,SEA,JFK,1547.0,1602,0.0,0.0
3,2016-01-04,1,2016,1,4,737.0,0.0,745,0.0,SEA,JFK,1551.0,1602,0.0,0.0
4,2016-01-05,1,2016,1,5,708.0,0.0,710,0.0,SEA,JFK,1524.0,1527,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877291,2017-12-17,4,2017,12,17,1024.0,0.0,1030,0.0,ORD,IAH,1314.0,1326,0.0,0.0
1877292,2017-12-17,4,2017,12,17,1148.0,0.0,1156,0.0,LAX,EWR,1939.0,2017,0.0,0.0
1877293,2017-12-17,4,2017,12,17,739.0,0.0,737,2.0,IAH,DEN,904.0,909,0.0,0.0
1877294,2017-12-17,4,2017,12,17,1632.0,0.0,1638,0.0,DFW,DEN,1727.0,1747,0.0,0.0
1877295,2017-12-17,4,2017,12,17,1007.0,0.0,1008,0.0,MCO,EWR,1222.0,1245,0.0,0.0

In [146]:
weather_cols = [
    "date",
    "time",
    "airport",
    "tempF",
    "WindSpeedKmph",
    "WindDirDegree",
    "WeatherCode",
    "precipMM",
    "Visibility",
    "Pressure",
    "Cloudcover",
    "DewPointF",
    "WindGustKmph",
    "Humidity",
]

In [147]:
def load_weather_data(year):
  weather_data = pd.DataFrame()
  for airport in airports:
    for month in range(1, 13):
      data_path = f"weather_data/{airport}"
      file_path = f"{data_path}/{year}-{month}.json"
      try:
        with open(file_path, "r") as f:
          try:
            data = json.load(f)
            weather_data_month = data.get('data')
            if weather_data_month:
              weather_list = weather_data_month.get('weather')
              if weather_list:
                df = pd.DataFrame(weather_list)
                df['airport'] = airport
                weather_data = pd.concat([weather_data, df], ignore_index=True)
          except json.JSONDecodeError:
            print(f"Error parsing JSON file: {file_path}")
            continue
      except FileNotFoundError:
        print(f"File not found: {file_path}")
  return weather_data

In [148]:
weather_data_2016 = load_weather_data(2016)
weather_data_2017 = load_weather_data(2017)

weather_data = pd.concat([weather_data_2016, weather_data_2017], ignore_index=True)

In [ ]:
weather_data

In [150]:
def merge_dicts(dicts):
    merged_dict = {}
    
    for dictionary in dicts:
        for key, value in dictionary.items():
            if key in merged_dict:
                merged_dict[key].append(value)
            else:
                merged_dict[key] = [value]
    
    for key, value in merged_dict.items():
        merged_dict[key] = value
    
    return merged_dict

In [151]:
hourly_list = []

for i in range(len(weather_data)):
    hourly_list.append(merge_dicts(weather_data['hourly'][i]))

In [152]:
df = pd.DataFrame(hourly_list)

In [154]:
weather_data_joined = pd.concat([weather_data, df], axis=1)

In [156]:
weather_data_joined.columns = weather_data_joined.columns.str.lower()
weather_cols_lower = [col.lower() for col in weather_cols]

In [157]:
weather_data_joined = weather_data_joined[weather_cols_lower]

In [175]:
weather_data_joined

,date,time,airport,tempf,windspeedkmph,winddirdegree,weathercode,precipmm,visibility,pressure,cloudcover,dewpointf,windgustkmph,humidity
0,2016-01-01,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",ATL,"[49, 46, 43, 40, 40, 40, 40, 41, 42, 42, 44, 4...","[11, 13, 14, 16, 17, 17, 18, 18, 17, 17, 17, 1...","[318, 317, 315, 314, 314, 315, 315, 317, 318, ...","[176, 176, 122, 122, 122, 122, 122, 122, 122, ...","[0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1023, 1023, 1023, 1023, 1023, 1024, 1024, 102...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[47, 44, 41, 38, 38, 38, 38, 38, 38, 39, 38, 3...","[17, 22, 26, 30, 30, 29, 28, 26, 23, 20, 20, 2...","[91, 92, 92, 93, 93, 93, 93, 93, 92, 92, 88, 8..."
1,2016-01-02,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",ATL,"[40, 39, 38, 38, 37, 36, 35, 35, 36, 36, 37, 3...","[15, 16, 16, 16, 16, 16, 16, 15, 15, 14, 14, 1...","[319, 320, 321, 322, 319, 316, 314, 314, 315, ...","[122, 122, 116, 116, 116, 122, 122, 122, 122, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1026, 1026, 1026, 1026, 1026, 1026, 1027, 102...","[86, 81, 76, 71, 79, 88, 97, 92, 87, 82, 68, 5...","[33, 33, 33, 33, 32, 32, 31, 31, 31, 30, 30, 3...","[23, 23, 23, 23, 23, 23, 23, 22, 21, 19, 18, 1...","[76, 78, 80, 83, 83, 84, 85, 84, 84, 83, 79, 7..."
2,2016-01-03,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",ATL,"[41, 41, 40, 40, 40, 39, 39, 39, 39, 39, 41, 4...","[10, 10, 10, 10, 11, 11, 11, 10, 10, 10, 10, 1...","[293, 297, 301, 306, 307, 309, 310, 309, 308, ...","[116, 116, 122, 122, 122, 113, 113, 113, 122, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1024, 1023, 1023, 1022, 1022, 1022, 1021, 102...","[50, 56, 62, 68, 57, 47, 37, 54, 70, 87, 81, 7...","[34, 34, 34, 34, 33, 33, 33, 32, 32, 31, 31, 3...","[15, 16, 16, 17, 16, 16, 16, 16, 15, 14, 14, 1...","[75, 76, 77, 78, 79, 80, 81, 80, 79, 78, 74, 6..."
3,2016-01-04,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",ATL,"[42, 41, 41, 40, 38, 37, 36, 35, 33, 32, 33, 3...","[13, 14, 14, 15, 15, 15, 15, 16, 16, 17, 18, 1...","[310, 312, 315, 317, 317, 316, 316, 318, 320, ...","[116, 116, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1018, 1018, 1018, 1018, 1018, 1019, 1019, 101...","[39, 26, 13, 0, 2, 5, 7, 20, 34, 47, 55, 62, 7...","[33, 34, 34, 34, 33, 33, 32, 31, 30, 30, 29, 2...","[21, 21, 21, 21, 21, 21, 22, 22, 23, 24, 24, 2...","[70, 73, 76, 80, 82, 85, 88, 89, 91, 92, 89, 8..."
4,2016-01-05,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",ATL,"[35, 35, 35, 35, 34, 34, 33, 33, 33, 33, 34, 3...","[12, 11, 11, 10, 9, 9, 9, 9, 10, 10, 11, 12, 1...","[14, 23, 32, 41, 45, 49, 53, 56, 59, 62, 66, 6...","[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1030, 1031, 1031, 1031, 1031, 1032, 1032, 103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[28, 29, 29, 30, 29, 29, 28, 27, 25, 24, 23, 2...","[15, 14, 12, 11, 11, 11, 10, 11, 11, 12, 13, 1...","[77, 79, 81, 84, 83, 83, 82, 79, 75, 72, 66, 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10960,2017-12-27,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",SFO,"[49, 49, 49, 48, 48, 48, 47, 47, 47, 46, 47, 4...","[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 7, ...","[320, 326, 332, 337, 302, 267, 232, 156, 81, 5...","[248, 248, 248, 248, 248, 248, 248, 248, 143, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1024, 1025, 1025, 1025, 1025, 1025, 1025, 102...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[49, 48, 48, 48, 47, 47, 46, 46, 46, 46, 46, 4...","[8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 9, ...","[97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 96, 9..."
10961,2017-12-28,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",SFO,"[48, 47, 45, 43, 43, 42, 42, 42, 43, 43, 44, 4...","[5, 3, 2, 0, 1, 1, 1, 2, 3, 4, 5, 6, 8, 8, 8, ...","[18, 21, 24, 28, 27, 27, 27, 23, 19, 15, 17, 1...","[143, 143, 122, 122, 122, 143, 143, 143, 122, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1024, 1024, 1024, 1024, 1024, 1024, 1024, 102...","[57, 65, 74, 83, 86, 89, 93, 94, 96, 97, 94, 9...","[47, 46, 44, 42, 42, 41, 41, 41, 42, 43, 43, 4...","[14, 14, 15, 15, 16, 16, 16, 16, 15, 15, 14, 1...","[96, 96, 96, 97, 97, 97, 97, 97, 97, 97, 96, 9..."
10962,2017-12-29,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",SFO,"[52, 51, 51, 50, 49, 49, 48, 48, 48, 48, 50, 5...","[8, 8, 8, 8, 7, 7, 6, 6, 5, 4, 5, 6, 7, 8, 8, ...","[23, 23, 23, 24, 26, 29, 31, 31, 32, 32, 30, 2...","[122, 122, 116, 116, 116, 116, 116, 116, 116, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1022, 1022, 1022, 1022, 1022, 1022, 1022, 102...","[46, 58, 70, 83, 71, 60, 48, 42, 35, 29, 31, 3...","[47, 47, 47, 46, 46, 46, 46, 46, 45, 45, 45, 4...","[18, 19, 19, 19, 20, 20, 20, 19, 19, 18, 16, 1...","[83, 84, 86, 88, 89, 90, 91, 90, 89, 89, 85, 8..."
10963,2017-12-30,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",SFO,"[52, 51, 50, 49, 48, 47, 45, 44, 43, 42, 44, 4...","[6, 5, 5, 4, 3, 2, 1, 2, 3, 4, 5, 7, 8, 8, 8, ...","[14, 18, 22, 26, 25, 24, 23, 25, 28, 30, 31, 3...","[143, 143, 248, 248, 248, 143, 143, 143, 143, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1021, 1021, 1020, 1020, 1020, 1020, 1020, 102...","[38, 42, 46, 51, 67, 83, 99, 98, 98, 97, 98, 9...","[48, 48, 48, 48, 47, 46, 44, 43, 42, 41, 42, 4...","[12, 13, 13, 14, 15, 16, 17, 17, 17, 17, 15, 1...","[88, 90, 93, 96, 96, 97, 98, 97, 97, 96, 94, 9..."
10964,2017-12-31,"[0, 100, 200, 300, 400, 500, 600, 700, 800, 90...",SFO,"[51, 51, 51, 50, 50, 50, 50, 50, 51, 51, 52, 5...","[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 5, ...","[50, 64, 77, 91, 91, 92, 93, 117, 142, 167, 22...","[119, 119, 119, 119, 119, 122, 122, 122, 116, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1016, 1016, 1016, 1016, 1016, 1016, 1017, 101...","[89, 87, 85, 83, 85, 87, 90, 86, 83, 79, 71, 6...","[47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 48, 4...","[6, 6, 6, 6, 6, 7, 7, 8, 8, 9, 8, 7, 6, 6, 6, ...","[85, 86, 87, 88, 89, 89, 89, 88, 86, 85, 85, 8..."

In [177]:
merged_data = pd.merge(flight_data, weather_data_joined, left_on=['FlightDate', 'Origin'], right_on=['date','airport'])
merged_data.to_csv('merged_data.csv', index=False)

In [179]:
merged_data

,FlightDate,Quarter,Year,Month,DayofMonth,DepTime,DepDel15,CRSDepTime,DepDelayMinutes,Origin,...,windspeedkmph,winddirdegree,weathercode,precipmm,visibility,pressure,cloudcover,dewpointf,windgustkmph,humidity
0,2016-01-01,1,2016,1,1,741.0,0.0,745,0.0,SEA,...,"[7, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 5, ...","[106, 106, 106, 106, 106, 106, 106, 107, 108, ...","[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1033, 1032, 1032, 1031, 1031, 1031, 1030, 103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[23, 23, 24, 25, 25, 24, 24, 23, 23, 22, 23, 2...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 6, 6, ...","[58, 61, 64, 67, 67, 67, 67, 66, 65, 64, 62, 6..."
1,2016-01-01,1,2016,1,1,1043.0,0.0,1047,0.0,SEA,...,"[7, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 5, ...","[106, 106, 106, 106, 106, 106, 106, 107, 108, ...","[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1033, 1032, 1032, 1031, 1031, 1031, 1030, 103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[23, 23, 24, 25, 25, 24, 24, 23, 23, 22, 23, 2...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 6, 6, ...","[58, 61, 64, 67, 67, 67, 67, 66, 65, 64, 62, 6..."
2,2016-01-01,1,2016,1,1,835.0,0.0,830,5.0,SEA,...,"[7, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 5, ...","[106, 106, 106, 106, 106, 106, 106, 107, 108, ...","[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1033, 1032, 1032, 1031, 1031, 1031, 1030, 103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[23, 23, 24, 25, 25, 24, 24, 23, 23, 22, 23, 2...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 6, 6, ...","[58, 61, 64, 67, 67, 67, 67, 66, 65, 64, 62, 6..."
3,2016-01-01,1,2016,1,1,2311.0,0.0,2315,0.0,SEA,...,"[7, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 5, ...","[106, 106, 106, 106, 106, 106, 106, 107, 108, ...","[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1033, 1032, 1032, 1031, 1031, 1031, 1030, 103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[23, 23, 24, 25, 25, 24, 24, 23, 23, 22, 23, 2...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 6, 6, ...","[58, 61, 64, 67, 67, 67, 67, 66, 65, 64, 62, 6..."
4,2016-01-01,1,2016,1,1,455.0,0.0,500,0.0,SEA,...,"[7, 7, 7, 6, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 5, ...","[106, 106, 106, 106, 106, 106, 106, 107, 108, ...","[113, 113, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1033, 1032, 1032, 1031, 1031, 1031, 1030, 103...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[23, 23, 24, 25, 25, 24, 24, 23, 23, 22, 23, 2...","[8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 6, 6, ...","[58, 61, 64, 67, 67, 67, 67, 66, 65, 64, 62, 6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877291,2017-12-25,4,2017,12,25,1819.0,1.0,1622,117.0,IAH,...,"[17, 15, 13, 12, 10, 9, 7, 9, 12, 14, 14, 13, ...","[34, 35, 37, 38, 42, 47, 51, 56, 62, 67, 76, 8...","[116, 116, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1029, 1029, 1030, 1030, 1030, 1030, 1030, 103...","[13, 9, 4, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 8, 15...","[38, 38, 38, 38, 38, 37, 37, 36, 35, 34, 34, 3...","[26, 26, 25, 25, 23, 22, 20, 19, 18, 18, 17, 1...","[78, 80, 82, 83, 85, 86, 87, 83, 80, 77, 71, 6..."
1877292,2017-12-25,4,2017,12,25,1949.0,0.0,1957,0.0,IAH,...,"[17, 15, 13, 12, 10, 9, 7, 9, 12, 14, 14, 13, ...","[34, 35, 37, 38, 42, 47, 51, 56, 62, 67, 76, 8...","[116, 116, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1029, 1029, 1030, 1030, 1030, 1030, 1030, 103...","[13, 9, 4, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 8, 15...","[38, 38, 38, 38, 38, 37, 37, 36, 35, 34, 34, 3...","[26, 26, 25, 25, 23, 22, 20, 19, 18, 18, 17, 1...","[78, 80, 82, 83, 85, 86, 87, 83, 80, 77, 71, 6..."
1877293,2017-12-25,4,2017,12,25,609.0,0.0,615,0.0,IAH,...,"[17, 15, 13, 12, 10, 9, 7, 9, 12, 14, 14, 13, ...","[34, 35, 37, 38, 42, 47, 51, 56, 62, 67, 76, 8...","[116, 116, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1029, 1029, 1030, 1030, 1030, 1030, 1030, 103...","[13, 9, 4, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 8, 15...","[38, 38, 38, 38, 38, 37, 37, 36, 35, 34, 34, 3...","[26, 26, 25, 25, 23, 22, 20, 19, 18, 18, 17, 1...","[78, 80, 82, 83, 85, 86, 87, 83, 80, 77, 71, 6..."
1877294,2017-12-25,4,2017,12,25,2059.0,1.0,2026,33.0,IAH,...,"[17, 15, 13, 12, 10, 9, 7, 9, 12, 14, 14, 13, ...","[34, 35, 37, 38, 42, 47, 51, 56, 62, 67, 76, 8...","[116, 116, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1029, 1029, 1030, 1030, 1030, 1030, 1030, 103...","[13, 9, 4, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 8, 15...","[38, 38, 38, 38, 38, 37, 37, 36, 35, 34, 34, 3...","[26, 26, 25, 25, 23, 22, 20, 19, 18, 18, 17, 1...","[78, 80, 82, 83, 85, 86, 87, 83, 80, 77, 71, 6..."
1877295,2017-12-25,4,2017,12,25,748.0,0.0,750,0.0,IAH,...,"[17, 15, 13, 12, 10, 9, 7, 9, 12, 14, 14, 13, ...","[34, 35, 37, 38, 42, 47, 51, 56, 62, 67, 76, 8...","[116, 116, 113, 113, 113, 113, 113, 113, 113, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 1...","[1029, 1029, 1030, 1030, 1030, 1030, 1030, 103...","[13, 9, 4, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 8, 15...","[38, 38, 38, 38, 38, 37, 37, 36, 35, 34, 34, 3...","[26, 26, 25, 25, 23, 22, 20, 19, 18, 18, 17, 1...","[78, 80, 82, 83, 85, 86, 87, 83, 80, 77, 71, 6..."